version: "3.9"
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certificates:/etc/letsencrypt/certificates
      - html_vol:/var/www
  deployer:
    build: ./deployer
    ports:
      - 5000:5000
    volumes:
      - html_vol:/html
      - ./deployer:/app
volumes:
  html_vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/spiskorz/GitRepos/test/Resume-Online/html # configure this to match the html folder in our repo