version: "3.9"
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./fullchain.pem:/etc/letsencrypt/certificates/fullchain.pem
      - ./privkey.pem:/etc/letsencrypt/certificates/privkey.pem
      - ./ssl-dhparams.pem:/etc/letsencrypt/certificates/ssl-dhparams.pem
      - html_vol:/var/www
  deployer:
    build: ./deployer
    ports:
      - 5000:5000
    volumes:
      - html_vol:/html
      - ./deployer:/app
volumes:
  html_vol:
    driver: local
    driver_opts:
      o: volumes
      type: none
      device: ./html