name: Generate Resume

on:
  push:
    branches: [ master, main ]
    paths:
      - 'resume_data.yaml'
      - 'jinja_template.html'
      - 'generate_resume.py'
      - '.github/workflows/generate-resume.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'resume_data.yaml'
      - 'jinja_template.html'
      - 'generate_resume.py'
  workflow_dispatch: # Allow manual triggers

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build resume generator image
      run: |
        docker build -f Dockerfile.generator -t resume-generator .
    
    - name: Generate resume HTML
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/html:/app/html \
          -e GITHUB_TOKEN="${GITHUB_TOKEN}" \
          resume-generator
    
    - name: List generated files
      run: |
        echo "Generated files:"
        ls -la html/
    
    - name: Upload generated HTML as artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-resume
        path: html/index.html
        retention-days: 30
    
    - name: Commit and push changes (if on main/master)
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if [ -f html/index.html ]; then
          git add html/index.html
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Auto-update generated resume HTML
            
            Generated from:
            - resume_data.yaml
            - jinja_template.html
            
            Triggered by: ${{ github.event_name }}
            Commit: ${{ github.sha }}"
            
            git push
          fi
        else
          echo "❌ No HTML file generated"
          exit 1
        fi